# Generated by Django 4.0.4 on 2022-05-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(related_name='Жанр', to='catalog.genre'),
        ),
    ]
