# Generated by Django 4.0.4 on 2022-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='episode_duration',
            field=models.IntegerField(default=0, verbose_name='Длительность эпизода'),
        ),
        migrations.AddField(
            model_name='anime',
            name='episodes_number',
            field=models.IntegerField(default=0, verbose_name='Эпизоды'),
        ),
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(to='catalog.genre'),
        ),
    ]
