# Generated by Django 4.0.4 on 2022-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_comment_genre_anime_episode_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('i', 'Выходит'), ('o', 'Вышло')], default='i', max_length=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='date',
            field=models.DateField(help_text='Введите дату выхода аниме', verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание', max_length=100000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episode_duration',
            field=models.IntegerField(default=0, help_text='Введите длительность эпизода, мин.', verbose_name='Длительность эпизода'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_number',
            field=models.IntegerField(default=0, help_text='Введите количество эпизодов', verbose_name='Эпизоды'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Введите комментарий', max_length=100000),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Введите название жанра', max_length=100, verbose_name='Название'),
        ),
    ]
