# Generated by Django 4.0.4 on 2022-05-26 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0009_anime_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='rating',
            new_name='averageRating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, help_text='Введите число', verbose_name='Рейтинг')),
                ('anime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.anime')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
