# Generated by Django 4.0.4 on 2022-05-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_rating_user_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='averageRating',
            new_name='average_rating',
        ),
    ]
