# Generated by Django 4.0.4 on 2022-05-27 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0013_status_alter_anime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
