# Generated by Django 4.0.4 on 2022-05-30 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_anime_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.CharField(max_length=1000, validators=[django.core.validators.URLValidator(message='Введите ссылку на изображение')], verbose_name='Источник изображения'),
        ),
    ]
