# Generated by Django 4.0.4 on 2022-05-30 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_anime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='average_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Минимум 0'), django.core.validators.MaxValueValidator(limit_value=5, message='Максимум 5')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episode_duration',
            field=models.IntegerField(default=1, help_text='Введите длительность эпизода, мин.', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимум 1')], verbose_name='Длительность эпизода'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_number',
            field=models.IntegerField(default=1, help_text='Введите количество эпизодов', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимум 1')], verbose_name='Эпизоды'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='number',
            field=models.IntegerField(default=0, help_text='Введите число', validators=[django.core.validators.MinValueValidator(limit_value=0, message='Минимум 0'), django.core.validators.MaxValueValidator(limit_value=5, message='Максимум 5')], verbose_name='Рейтинг'),
        ),
    ]
